In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

In [136]:
"""
1 Указание: рекомендуется воспользоваться функцией genfromtxt. Обратите внимание, что данные в файлах разделены запятой, в обоих файлах есть заголовок, 
который при загрузке нужно пропустить. Для корректной загрузки названий стран необходимо также указать тип данных 
(по умолчанию загружаемые данные преобразуются в вещественный тип). Вы можете либо собрать все данные в один массив записей,
 либо работать с тремя разными массивами: массив названий стран (одномерный, строки), массивы производства и потребления энергии (двумерные, вещественные)).
"""
countries = np.genfromtxt(
    "global-electricity-consumption.csv",
    delimiter=',', 
    skip_header=1,
    usecols=0,  
    dtype=str,
    encoding='utf-8'
)

consumption_values = np.genfromtxt(
    "global-electricity-consumption.csv",
    delimiter=',', 
    skip_header=1,
    usecols=range(1, 31),
    dtype=float,
    encoding='utf-8'
)

generation_values = np.genfromtxt(
    "global-electricity-generation.csv",
    delimiter=',', 
    skip_header=1,
    usecols=range(1, 31),
    dtype=float,
    encoding='utf-8'
)

print("Страна:", countries[0])
print("Потребление:", consumption_values[0])
print("Производство:", generation_values[0])

Страна: Algeria
Потребление: [14.035      14.039      14.365      14.474      15.172      15.365
 16.905      18.492      19.71552    20.64764    21.62354    23.61164
 24.42506    27.5164     26.91052    28.3348     30.49982    28.315
 33.8405     38.13478    42.8675     45.2014     49.20572    53.45544
 55.82304    60.28346    62.11403    66.646      63.69490277 68.66337919]
Производство: [17.199      18.267      18.703      18.09       19.124      19.739
 21.448      23.282      23.88952    25.03064    25.99154    27.80964
 29.38706    31.9074     33.12352    34.9758     37.83582    36.206
 42.9985     48.17578    53.9845     56.3134     60.39972    64.68244
 66.75504    71.49546    72.10903    76.685      72.73591277 77.53072719]


In [61]:
consumption_last_5 = consumption_values[:, -5:]
print("последние 5 записей потребления электроэнергии по всем странам")
print("-" * 62 )
print(consumption_last_5)
generation_last_5 = generation_values[:, -5:]


последние 5 записей потребления электроэнергии по всем странам
--------------------------------------------------------------
[[60.28346    62.11403    66.646      63.69490277 68.66337919]
 [ 9.468667   11.384079   13.658591   14.754764   14.56049071]
 [ 1.125821    1.187964    0.9297      0.52408     0.52338299]
 ...
 [ 0.45824     0.56        0.568       0.5978      0.6415072 ]
 [11.098889   11.768859   11.713604   11.780227   13.61377336]
 [67.901917   65.258054   56.532821   70.47945808 71.04766385]]


In [ ]:
"""
2 Постройте одномерные массивы ежегодного производства и потребления электроэнергии в среднем за последние 5 лет 
(один массив – производство по всем странам, второй – потребление по всем странам).
Указание: не забывайте, что в агрегирующих функциях для построчной обработки нужно указывать параметр axis=1.
"""
average_generation_5_last = np.nanmean(generation_last_5, axis=1)

average_consumption_5_last = np.nanmean(consumption_last_5, axis=1)

print(f"{'Страна':<25} {'Потребление':<12} | {'Страна':<25} {'Производство':<12}")
print("-" * 39 + "+" + "-" * 39)
for i in range(len(countries)):
    print(f"{countries[i]:<25} {average_consumption_5_last[i]:12.2f} | {countries[i]:<25} {average_generation_5_last[i]:12.2f}")

Страна                    Потребление  | Страна                    Производство
---------------------------------------+---------------------------------------
Algeria                          64.28 | Algeria                          74.11
Angola                           12.77 | Angola                           14.39
Benin                             0.86 | Benin                             0.23
Botswana                          3.59 | Botswana                          2.62
Burkina Faso                      2.42 | Burkina Faso                      1.69
Burundi                           0.38 | Burundi                           0.32
Cabo Verde                        0.32 | Cabo Verde                        0.45
Cameroon                          6.30 | Cameroon                          8.16
Central African Republic          0.14 | Central African Republic          0.15
Chad                              0.26 | Chad                              0.30
Comoros                           0.08 |

C:\Temp\ipykernel_14696\3440804736.py:1: RuntimeWarning: Mean of empty slice
  average_generation_5_last = np.nanmean(generation_last_5, axis=1)


In [ ]:
"""
3.1 Суммарное (по всем странам) потребление электроэнергии за каждый год.
"""
total_consumption_by_year = np.nansum(consumption_values, axis=0)

years = np.arange(1992, 2022)
print(f"\n{'Год':<6} {'Потребление':<20}")
print("-" * 18)
for i, year in enumerate(years):
    print(f"{year:<6} {total_consumption_by_year[i]:<20.2f}")


Год    Потребление         
------------------
1992   10569.02            
1993   10854.56            
1994   11104.65            
1995   11476.48            
1996   11805.87            
1997   12122.03            
1998   12419.81            
1999   12685.75            
2000   13230.25            
2001   13486.49            
2002   13938.78            
2003   14455.56            
2004   15128.10            
2005   15725.98            
2006   16438.21            
2007   17205.12            
2008   17477.47            
2009   17435.69            
2010   18748.16            
2011   19438.82            
2012   19918.25            
2013   20573.10            
2014   20981.24            
2015   21400.02            
2016   22022.69            
2017   22716.21            
2018   23530.92            
2019   23915.66            
2020   23959.68            
2021   25336.71            


In [ ]:
"""
3.2 Максимальное количество электроэнергии, которое произвела одна страна за один год 
(указание: чтобы не учитывать отсутствующие и некорректные данные (nan) 
воспользуйтесь NaN-безопасной версией функции max, то есть nanmax).
"""
maximum_generation = np.nanmax(generation_values, axis=0)

max_country_indices = np.nanargmax(generation_values, axis=0)

years = np.arange(1992, 2022)
print(f"\n{'Год':<6} {'Макс. выработка':<16} {'Страна':<20}")
print("-" * 50)
for i, year in enumerate(years):
    country_idx = max_country_indices[i]
    country_name = countries[country_idx]
    max_value = maximum_generation[i]
    print(f"{year:<6} {max_value:<16.2f} {country_name:<20}")


Год    Макс. выработка  Страна              
--------------------------------------------------
1992   3083.93          United States       
1993   3197.24          United States       
1994   3247.58          United States       
1995   3353.55          United States       
1996   3444.26          United States       
1997   3492.25          United States       
1998   3620.38          United States       
1999   3694.91          United States       
2000   3802.22          United States       
2001   3736.78          United States       
2002   3858.62          United States       
2003   3883.38          United States       
2004   3970.80          United States       
2005   4055.79          United States       
2006   4065.23          United States       
2007   4157.49          United States       
2008   4120.59          United States       
2009   3951.94          United States       
2010   4127.60          United States       
2011   4465.48          China               
201

In [99]:
"""
3.3 Список стран, которые производят более 500 млрд. кВт*ч электроэнергии ежегодно в среднем за последние 5 лет (воспользуйтесь массивом, полученным на шаге 2).
"""
high_production_countries_index = np.where(average_generation_5_last > 500)[0]

print(f"Страны, производящие более {500} ТВт·ч ({500} млрд. кВт·ч) в среднем за 2017-2021 годы:")
print("=" * 70)
print(f"{'Страна':<25} {'Среднее производство (ТВт·ч)':<25}")
print("-" * 70)

for i in high_production_countries_index:
    print(f"{countries[i]:<25} {average_generation_5_last[i]:<25.2f}")

Страны, производящие более 500 ТВт·ч (500 млрд. кВт·ч) в среднем за 2017-2021 годы:
Страна                    Среднее производство (ТВт·ч)
----------------------------------------------------------------------
Russia                    1059.99                  
France                    533.22                   
Germany                   581.56                   
China                     7190.02                  
India                     1595.25                  
Japan                     983.88                   
South Korea               558.36                   
Canada                    631.61                   
United States             4130.27                  
Brazil                    614.18                   


In [131]:
"""
3.4. 10% стран, которые потребляют больше всего электроэнергии ежегодно в среднем за последние 5 лет 
(указание: вначале определите соответствующую квантиль в массиве, построенном на шаге 2).
"""

n_countries = len(countries)
top_10_percent = int(np.ceil(n_countries * 0.1))

sorted_indices_consu = np.argsort(-average_consumption_5_last)

top_indices = sorted_indices_consu[:top_10_percent]

print(f"Топ {top_10_percent} стран по потреблению электроэнергии")
print("=" * 70)
print(f"{'Страна':<25} {'Среднее потребление (ТВт·ч)':<25}")
print("-" * 70)

for i in top_indices:
    country = countries[i]
    consumption = average_consumption_5_last[i]
    print(f"{country:<25} {consumption:<25.2f}")


Топ 22 стран по потреблению электроэнергии
Страна                    Среднее потребление (ТВт·ч)
----------------------------------------------------------------------
China                     6846.21                  
United States             3957.50                  
India                     1330.94                  
Russia                    946.68                   
Japan                     940.32                   
Canada                    547.32                   
Brazil                    539.93                   
South Korea               539.51                   
Germany                   520.23                   
France                    445.22                   
Saudi Arabia              324.52                   
United Kingdom            303.54                   
Italy                     296.44                   
Mexico                    285.83                   
Iran                      282.51                   
Taiwan                    265.07                   


In [132]:
"""
3.5. Список стран, которые увеличили производство электроэнергии в 2021 году по сравнению с 1992 годом более, чем в 10 раз.
"""
all_in_1992 = generation_values[:, 0]
all_in_2021 = generation_values[:, -1]

# Избегаем деления на ноль, np.where(условие, значение_если_да, значение_если_нет)
all_in_1992_safe = np.where(all_in_1992 == 0, 0.001, all_in_1992)
growth_ratio = all_in_2021 / all_in_1992_safe

high_growth_indices = np.where(growth_ratio > 10)[0]

print(f"Страны, увеличившие производство электроэнергии более чем в 10 раз (2021 vs 1992)")
print("=" * 90)
print(f"{'Страна':<25} {'1992 год (ТВт·ч)':<15} {'2021 год (ТВт·ч)':<15} {'Рост (раз)':<12}")
print("-" * 90)

for i in high_growth_indices:
    print(f"{countries[i]:<25} {all_in_1992[i]:<15.2f} {all_in_2021[i]:<15.2f} {growth_ratio[i]:<12.1f}")

Страны, увеличившие производство электроэнергии более чем в 10 раз (2021 vs 1992)
Страна                    1992 год (ТВт·ч) 2021 год (ТВт·ч) Рост (раз)  
------------------------------------------------------------------------------------------
Angola                    1.28            16.43           12.8        
Benin                     0.02            0.24            10.5        
Equatorial Guinea         0.02            1.42            78.8        
Ethiopia                  1.22            14.68           12.0        
Lesotho                   0.00            0.50            501.2       
Mali                      0.27            3.39            12.5        
Mauritania                0.14            1.88            13.5        
Mozambique                0.41            19.91           48.8        
Namibia                   0.00            1.57            1567.2      
Sudan                     1.59            16.60           10.4        
Cambodia                  0.17            8.

In [ ]:
"""
3.6. Список стран, которые в сумме за все годы потратили больше 100 млрд. кВт*ч электроэнергии и при этом произвели меньше, чем потратили.
"""

total_consumption_by_all = np.nansum(consumption_values, axis = 1)
total_generation_by_all = np.nansum(generation_values, axis = 1)

idx_spent_more_100_and_gen_below = np.where((total_consumption_by_all > 100) & (total_consumption_by_all > total_generation_by_all))[0]

print(f"Страны с потреблением >100 ТВт·ч и дефицитом производства")
print("=" * 80)
print(f"{'Страна':<25} {'Потребление':<12} {'Производство':<12}")
print("-" * 80)

for i in idx_spent_more_100_and_gen_below:
    print(f"{countries[i]:<25} {total_consumption_by_all[i]:<12.2f} {total_generation_by_all[i]:<12.2f}")

print(f"\nВсего стран: {len(idx_spent_more_100_and_gen_below)}")

Страны с потреблением >100 ТВт·ч и дефицитом производства
Страна                    Потребление  Производство
--------------------------------------------------------------------------------
Zimbabwe                  260.62       238.18      
Belarus                   922.33       895.46      
Moldova                   202.82       180.22      
Belgium                   2395.91      2342.36     
Croatia                   418.57       342.39      
Finland                   2356.64      2069.42     
Hungary                   1066.96      981.68      
Italy                     8576.57      7879.03     
Latvia                    179.29       146.66      
Luxembourg                177.54       38.27       
Netherlands               3106.41      2896.51     
North Macedonia           186.88       177.76      
Hong Kong                 1152.85      998.42      

Всего стран: 13


In [158]:
"""
3.7. Какая страна потратила наибольшее количество электроэнергии в 2020 году?
"""

consumption_2020 = consumption_values[:, -2]

country_max_spent_2020 = np.argmax(consumption_2020)

print(f"Страна с максимальным потреблением в 2020 году: {countries[country_max_spent_2020]}")
print(f"Потребление: {consumption_2020[country_max_spent_2020]:.2f} ТВт·ч")


Страна с максимальным потреблением в 2020 году: China
Потребление: 7115.08 ТВт·ч
