In [2]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats


In [24]:
"""
Сгенерировать два одномерных массива m1 и m2 размерностью 10 (значения от 1 до 10).
"""
m1 = np.random.randint(1, 11, 10)
m2 = np.random.randint(1, 11, 10)

print("m1 = ", m1)
print("m1 = ", m2)

m1 =  [ 3  6 10  7  6  9  4  2  4  9]
m1 =  [6 5 6 6 2 6 4 9 2 4]


In [25]:
"""
1. Сформировать на их основе массивm3, содержащий только те элементы, которые есть либо только в массиве m1, либо только в массиве m2.
"""

m3 = np.setxor1d(m1, m2)

print("m3 :", m3)

m3 : [ 3  5  7 10]


In [26]:
"""
2. Заменить в первом массиве все значения, кратные 3 или 2 на число 1, а остальные – оставить без изменений.
"""

replaced_m1 = np.where((m1 % 3 == 0) | (m1 % 2 == 0), 1, m1)
print("После замены:", replaced_m1)

После замены: [1 1 1 7 1 1 1 1 1 1]


In [27]:
"""
3. Слить массивыm1 и m2 в один и преобразовать получившийся одномерный массив в матрицу размерностью 4х5. Вывести ее на экран.
"""

merged = np.concatenate([m1, m2])
print("\nОбъединенный массив:", merged)

matrix_4x5 = merged.reshape(4, 5)
print("\nМатрица 4×5:")
print(matrix_4x5)


Объединенный массив: [ 3  6 10  7  6  9  4  2  4  9  6  5  6  6  2  6  4  9  2  4]

Матрица 4×5:
[[ 3  6 10  7  6]
 [ 9  4  2  4  9]
 [ 6  5  6  6  2]
 [ 6  4  9  2  4]]


In [29]:
"""
4. Удалить из матрицы 1 и 4 столбцы.
"""

#matrix_without_cols = matrix_4x5[:, [1, 2, 4]]
matrix_without_cols = np.delete(matrix_4x5, [0, 3], axis=1)
print("\nПосле удаления 1 и 4 столбцов (3×3):")
print(matrix_without_cols)


После удаления 1 и 4 столбцов (3×3):
[[ 6 10  6]
 [ 4  2  9]
 [ 5  6  2]
 [ 4  9  4]]


In [31]:
"""
5. Транспонировать полученную матрицу.
"""

transposed_matrix = np.transpose(matrix_without_cols)
print(transposed_matrix)

[[ 6  4  5  4]
 [10  2  6  9]
 [ 6  9  2  4]]
